# Generated by Django 4.1.2 on 2022-11-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upload',
            field=models.FileField(default='uploads/', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
