# Generated by Django 4.1.2 on 2022-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='uploads/'),
        ),
    ]
